// Auto-generated by scripts/make_schedule_headers.py
// Source schedule: traces/run027_reporting_txb_usefulness_threshold_schedule.csv
// Do not edit by hand; edit the schedule CSV and regenerate.
// Contains both SEND and SKIP rows for skipped-slot replay.

#ifndef SCHEDULE_DATA_TXB_H
#define SCHEDULE_DATA_TXB_H

#include <stdint.h>

struct ScheduleRow {
  uint16_t demand_index;
  char region;
  uint8_t event;
  float priority;
  float usefulness;
  uint16_t stale_after;
  char policy;
  uint8_t send;
};

static const uint16_t SCHEDULE_ROW_COUNT = 16;
static const uint16_t SCHEDULE_SEND_COUNT = 12;
static const uint16_t SCHEDULE_SKIP_COUNT = 4;

static const ScheduleRow SCHEDULE_ROWS[] = {
  {0, 'A', 1, 0.950f, 0.920f, 5, 'U', 1},
  {1, 'B', 0, 0.200f, 0.180f, 5, 'U', 0},
  {2, 'C', 1, 0.880f, 0.840f, 5, 'U', 1},
  {3, 'D', 0, 0.350f, 0.420f, 5, 'U', 1},
  {4, 'E', 1, 0.750f, 0.790f, 5, 'U', 1},
  {5, 'F', 0, 0.100f, 0.080f, 5, 'U', 0},
  {6, 'G', 1, 0.650f, 0.670f, 5, 'U', 1},
  {7, 'H', 0, 0.480f, 0.490f, 5, 'U', 1},
  {8, 'A', 1, 0.900f, 0.910f, 5, 'U', 1},
  {9, 'B', 0, 0.220f, 0.210f, 5, 'U', 0},
  {10, 'C', 1, 0.820f, 0.770f, 5, 'U', 1},
  {11, 'D', 0, 0.400f, 0.360f, 5, 'U', 1},
  {12, 'E', 1, 0.720f, 0.740f, 5, 'U', 1},
  {13, 'F', 0, 0.120f, 0.150f, 5, 'U', 0},
  {14, 'G', 1, 0.690f, 0.630f, 5, 'U', 1},
  {15, 'H', 0, 0.440f, 0.460f, 5, 'U', 1},
};

#endif  // SCHEDULE_DATA_TXB_H
