// Auto-generated by scripts/make_trace_headers.py
// Source trace: traces/run022_reporting_txb_usefulness_threshold_compact.csv
// Do not edit by hand; edit the CSV trace and regenerate.

#ifndef TRACE_DATA_TXB_H_
#define TRACE_DATA_TXB_H_

#include <stdint.h>

struct TraceRow {
  uint16_t seq;
  char region;
  uint8_t event;
  float priority;
  float usefulness;
  uint16_t stale_after;
  char policy;
};

static const uint16_t TRACE_ROW_COUNT = 8;

static const TraceRow TRACE_ROWS[] = {
  {0, 'A', 1, 0.950f, 0.920f, 5, 'U'},
  {1, 'C', 1, 0.880f, 0.840f, 5, 'U'},
  {2, 'E', 1, 0.750f, 0.790f, 5, 'U'},
  {3, 'G', 1, 0.650f, 0.670f, 5, 'U'},
  {4, 'A', 1, 0.900f, 0.910f, 5, 'U'},
  {5, 'C', 1, 0.820f, 0.770f, 5, 'U'},
  {6, 'E', 1, 0.720f, 0.740f, 5, 'U'},
  {7, 'G', 1, 0.690f, 0.630f, 5, 'U'},
};

#endif  // TRACE_DATA_TXB_H_
