#!/usr/bin/env python3
"""
Convert a small packet-metadata trace CSV into a C/C++ header for Arduino firmware.

Input CSV fields:

    seq,region,event,priority,usefulness,stale_after,policy

The generated header defines:

    struct TraceRow
    TRACE_ROWS[]
    TRACE_ROW_COUNT

This supports compiled-in trace replay before moving to SD-card replay.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


REQUIRED_FIELDS = [
    "seq",
    "region",
    "event",
    "priority",
    "usefulness",
    "stale_after",
    "policy",
]


def _char_value(value: str, field: str, row_number: int) -> str:
    value = str(value).strip()
    if len(value) != 1:
        raise ValueError(
            f"Row {row_number}: field '{field}' must be a single character, got {value!r}"
        )
    if value == "'":
        raise ValueError(f"Row {row_number}: field '{field}' cannot be a single quote")
    return value


def _validate_and_load(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open(newline="") as f:
        reader = csv.DictReader(f)

        missing = [name for name in REQUIRED_FIELDS if name not in (reader.fieldnames or [])]
        if missing:
            raise ValueError(f"{csv_path} is missing required fields: {missing}")

        rows: list[dict[str, str]] = []

        for i, row in enumerate(reader, start=2):  # header is line 1
            seq = int(row["seq"])
            event = int(row["event"])
            priority = float(row["priority"])
            usefulness = float(row["usefulness"])
            stale_after = int(row["stale_after"])

            if seq < 0:
                raise ValueError(f"Row {i}: seq must be non-negative")
            if event not in (0, 1):
                raise ValueError(f"Row {i}: event must be 0 or 1")
            if not (0.0 <= priority <= 1.0):
                raise ValueError(f"Row {i}: priority must be in [0, 1]")
            if not (0.0 <= usefulness <= 1.0):
                raise ValueError(f"Row {i}: usefulness must be in [0, 1]")
            if stale_after < 0:
                raise ValueError(f"Row {i}: stale_after must be non-negative")

            region = _char_value(row["region"], "region", i)
            policy = _char_value(row["policy"], "policy", i)

            rows.append(
                {
                    "seq": str(seq),
                    "region": region,
                    "event": str(event),
                    "priority": f"{priority:.3f}",
                    "usefulness": f"{usefulness:.3f}",
                    "stale_after": str(stale_after),
                    "policy": policy,
                }
            )

    if not rows:
        raise ValueError(f"{csv_path} contains no trace rows")

    return rows


def _header_guard(output_path: Path) -> str:
    stem = output_path.name.upper()
    cleaned = []
    for ch in stem:
        cleaned.append(ch if ch.isalnum() else "_")
    return "".join(cleaned) + "_"


def write_header(csv_path: Path, output_path: Path) -> None:
    rows = _validate_and_load(csv_path)
    guard = _header_guard(output_path)

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", newline="\n") as f:
        f.write("// Auto-generated by scripts/make_trace_headers.py\n")
        f.write(f"// Source trace: {csv_path.as_posix()}\n")
        f.write("// Do not edit by hand; edit the CSV trace and regenerate.\n\n")
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("struct TraceRow {\n")
        f.write("  uint16_t seq;\n")
        f.write("  char region;\n")
        f.write("  uint8_t event;\n")
        f.write("  float priority;\n")
        f.write("  float usefulness;\n")
        f.write("  uint16_t stale_after;\n")
        f.write("  char policy;\n")
        f.write("};\n\n")

        f.write(f"static const uint16_t TRACE_ROW_COUNT = {len(rows)};\n\n")
        f.write("static const TraceRow TRACE_ROWS[] = {\n")

        for row in rows:
            f.write(
                "  "
                "{"
                f"{row['seq']}, "
                f"'{row['region']}', "
                f"{row['event']}, "
                f"{row['priority']}f, "
                f"{row['usefulness']}f, "
                f"{row['stale_after']}, "
                f"'{row['policy']}'"
                "},\n"
            )

        f.write("};\n\n")
        f.write(f"#endif  // {guard}\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--infile", required=True, type=Path)
    parser.add_argument("--outfile", required=True, type=Path)
    args = parser.parse_args()

    write_header(args.infile, args.outfile)
    print(f"Wrote {args.outfile}")


if __name__ == "__main__":
    main()
