// Auto-generated by scripts/make_trace_headers.py
// Source trace: traces/run020_adapter_txa_fixed_all.csv
// Do not edit by hand; edit the CSV trace and regenerate.

#ifndef TRACE_DATA_TXA_H_
#define TRACE_DATA_TXA_H_

#include <stdint.h>

struct TraceRow {
  uint16_t seq;
  char region;
  uint8_t event;
  float priority;
  float usefulness;
  uint16_t stale_after;
  char policy;
};

static const uint16_t TRACE_ROW_COUNT = 16;

static const TraceRow TRACE_ROWS[] = {
  {0, 'A', 1, 0.950f, 0.920f, 5, 'F'},
  {1, 'B', 0, 0.200f, 0.180f, 5, 'F'},
  {2, 'C', 1, 0.880f, 0.840f, 5, 'F'},
  {3, 'D', 0, 0.350f, 0.420f, 5, 'F'},
  {4, 'E', 1, 0.750f, 0.790f, 5, 'F'},
  {5, 'F', 0, 0.100f, 0.080f, 5, 'F'},
  {6, 'G', 1, 0.650f, 0.670f, 5, 'F'},
  {7, 'H', 0, 0.480f, 0.490f, 5, 'F'},
  {8, 'A', 1, 0.900f, 0.910f, 5, 'F'},
  {9, 'B', 0, 0.220f, 0.210f, 5, 'F'},
  {10, 'C', 1, 0.820f, 0.770f, 5, 'F'},
  {11, 'D', 0, 0.400f, 0.360f, 5, 'F'},
  {12, 'E', 1, 0.720f, 0.740f, 5, 'F'},
  {13, 'F', 0, 0.120f, 0.150f, 5, 'F'},
  {14, 'G', 1, 0.690f, 0.630f, 5, 'F'},
  {15, 'H', 0, 0.440f, 0.460f, 5, 'F'},
};

#endif  // TRACE_DATA_TXA_H_
